FROM public.ecr.aws/lambda/python:3.13
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
# https://github.com/aws/aws-lambda-runtime-interface-emulator/tree/develop
RUN curl -Lo aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie
RUN chmod +x aws-lambda-rie
ENV APP_ENV=local
ENTRYPOINT ["/usr/local/bin/aws-lambda-rie", "python3", "-m", "awslambdaric"]
CMD ["app.handler"]
